send:
  name: Send Notification
  description: Send TTS and text message to selected devices
  fields:
    mode:
      name: Mode
      description: Whether to send to all device trackers or a specific person
      required: true
      selector:
        select:
          options:
            - "all"
            - "person"
    person:
      name: Person
      description: Person entity_id (if mode is person)
      required: false
      selector:
        entity:
          domain: person
    tts_text:
      name: TTS Message
      description: Text for TTS message
      required: true
      selector:
        text:
    tts_message_channel:
      name: TTS Channel
      description: Channel for TTS message
      required: true
      selector:
        text:
    text_message:
      name: Text Message
      description: Standard text message
      required: true
      selector:
        text:
    text_message_channel:
      name: Text Channel
      description: Channel for text message
      required: true
      selector:
        text:
